Site/Controllers/DeploymentController.cs
using System.Web.Mvc;
using SiteServices.ViewModelProviders;
using Contract;
using Web.Core;

namespace Site.Controllers
{
    public class DeploymentController : Controller
    {
        private readonly IDeploymentViewModelProvider _deploymentViewModelProvider;
        private readonly ILoggingService _loggingService;

        public DeploymentController(IDeploymentViewModelProvider deploymentViewModelProvider, ILoggingService loggingService)
        {
            _deploymentViewModelProvider = deploymentViewModelProvider;
            _loggingService = loggingService;
        }

        public ActionResult Index()
        {
            return View(_deploymentViewModelProvider.GetDeploymentsViewModel());
        }

        public ActionResult Create()
        {
            return View();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Create(Contract.Models.Deployment deployment)
        {
            _loggingService.Info("Deployment is being created.");
            return RedirectToAction("Index");
        }
    }
}

Site/Views/Deployment/Create.cshtml
@model Contract.Models.Deployment

@{
    ViewBag.Title = "Create Deployment";
}

<h1>Create Deployment</h1>
@using (Html.BeginForm())
{
    @Html.LabelFor(x => x.Name)
    @Html.TextBoxFor(x => x.Name)
    @Html.LabelFor(x => x.Description)
    @Html.TextBoxFor(x => x.Description)
    <input type="submit" value="Create">
}

Site/Views/Deployment/Index.cshtml
@model SiteServices.ViewModels.DeploymentsViewModel

@{
    ViewBag.Title = "Home Page";
}

<h1>Deployment Manager!</h1>

<div class="panel panel-default">
    <div class="panel-heading">
        <h2>
                Available Deployments <small><a href="@Url.Action("Create", "Deployment")">New Deployment</a></small>
        </h2>
    </div>
    <div class="panel-body">
        <div class="list-group">
            @foreach (var deployment in Model.Deployments)
            {
                <a href="@Url.Action("Details", "Deployment", new { deploymentId = deployment.DeploymentId })" class="list-group-item">
                    <h4 class="list-group-item-heading">@deployment.Name</h4>
                    <p class="list-group-item-text">@deployment.Description</p>
                </a>
            }
        </div>
    </div>
</div>